# Generated by Django 2.0 on 2020-10-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cornelius_User',
            new_name='CorneliusUser',
        ),
    ]
