# Generated by Django 3.1.2 on 2020-10-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0002_auto_20201010_1553'),
    ]

    operations = [
       
    ]
