# Generated by Django 2.0 on 2020-10-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0003_auto_20201018_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corneliususer',
            options={},
        ),
        migrations.RemoveField(
            model_name='corneliususer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='did',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cornelius_app.CorneliusUser'),
        ),
    ]
