# Generated by Django 2.0 on 2020-10-21 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0004_auto_20201021_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corneliususer',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='corneliususer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='doctor',
            table=None,
        ),
    ]
