# Generated by Django 2.0 on 2020-10-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0005_auto_20201021_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='did',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fid',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cornelius_app.corneliususer',),
        ),
    ]
