# Generated by Django 2.0 on 2020-10-21 04:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0006_auto_20201021_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cornelius_app.CorneliusUser', unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fid', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.DO_NOTHING, to='cornelius_app.Facility')),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='DoctorPatientMeeting',
            name='did',
            field=models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.DO_NOTHING, to='cornelius_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='MeetingInfo',
            name='did',
            field=models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.DO_NOTHING, to='cornelius_app.Doctor'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cornelius_app.corneliususer',),
        ),
    ]
