# Generated by Django 2.0 on 2020-10-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0009_auto_20201021_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fid',
            field=models.ForeignKey(blank=True, db_column='fid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cornelius_app.Facility'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='did',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cornelius_app.CorneliusUser'),
        ),
    ]
