# Generated by Django 2.0 on 2020-10-21 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0011_auto_20201021_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corneliususer',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='meetinginfo',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='meetinginfo',
            name='id',
        ),
        migrations.AddField(
            model_name='corneliususer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetinginfo',
            name='mid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
