# Generated by Django 3.1.2 on 2020-10-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0012_auto_20201021_1305'),
    ]

    operations = [
        
    ]
