# Generated by Django 2.0 on 2020-10-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0012_auto_20201021_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientmeeting',
            name='did',
        ),
        migrations.RemoveField(
            model_name='doctorpatientmeeting',
            name='pid',
        ),
        migrations.AlterModelOptions(
            name='corneliususer',
            options={},
        ),
        migrations.RemoveField(
            model_name='corneliususer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='visitjournal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitjournal',
            name='pid',
        ),
        migrations.AddField(
            model_name='visitjournal',
            name='mid',
            field=models.ForeignKey(db_column='mid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cornelius_app.MeetingInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingscript',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cornelius_app.MeetingInfo'),
        ),
        migrations.DeleteModel(
            name='DoctorPatientMeeting',
        ),
    ]
