# Generated by Django 3.1.2 on 2020-10-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0014_auto_20201022_2253'),
    ]

    operations = [
       
    ]
