# Generated by Django 2.0 on 2020-11-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cornelius_app', '0003_doctorpatientmeeting_meetinginfo_meetingscript_patient_visitjournal'),
        ('cornelius_app', '0015_auto_20201022_2258'),
        ('cornelius_app', '0013_auto_20201022_2023'),
    ]

    operations = [
    ]
